### ISSUE TITLE
Release `abstract-level` and dependents

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-level#14]
- [x] https://github.com/Level/community/pull/109
- [x] `abstract-level` (replacement for `abstract-leveldown` and more)
  - [x] 1.0.0
- [x] `memory-level` (replacement for `memdown` and `level-mem`)
  - [x] Create repository
  - [x] Replace links to `level-mem` and `memdown` in `Level/community`
  - [x] 1.0.0
- [x] `level-read-stream`
  - [x] https://github.com/Level/read-stream/issues/1 (needs `memory-level` for tests)
  - [x] Bump `engines.node` in `package.json`
  - [x] 1.0.1
- [x] `classic-level` (replacement for `leveldown`)
  - [x] Create repository
  - [x] Figure out how `nextv()` and `_landed` logic should interact
  - [x] Replace links to `leveldown` in `Level/community`
  - [x] https://github.com/Level/classic-level/pull/1
  - [x] https://github.com/Level/classic-level/pull/3
  - [x] https://github.com/prebuild/docker-images/pull/23
  - [x] https://github.com/prebuild/prebuildify-cross/pull/12
  - [x] 1.0.0
- [x] `browser-level` (replacement for `level-js`)
  - [x] Create repository
  - [x] Replace links to `level-js` in `Level/community`
  - [x] 1.0.0
- [x] `level`
  - [x] Optionally https://github.com/Level/classic-level/pull/6
  - [x] https://github.com/Level/level/pull/215
  - [x] 8.0.0
- [x] ~~`rocks-level`~~ (https://github.com/Level/community/pull/141)
- [x] `many-level` (replacement for `multileveldown`)
  - [x] https://github.com/Level/abstract-level/pull/20
  - [x] https://github.com/Level/abstract-level/pull/21
  - [x] 1.0.0
- [x] `rave-level` (replacement for `level-party`, depends on `level@8`)
  - [x] https://github.com/Level/classic-level/pull/8
  - [x] 1.0.0

Side tasks:

- [ ] Add npm owners (also to [`level-web-stream`](https://github.com/Level/web-stream))
- [x] https://github.com/Level/webpack-starter/commit/c6db89d513288cf90a8cb77f81c7500e63ce021f
- [x] https://github.com/Level/browserify-starter/commit/2afa2c0f3aa2bbe58fc9383759acd35b027902d0
- [x] https://github.com/Level/level-ws/commit/94a2a8ef0be0dd96cc9de9ca250d4bc5878ffc5b

**Comment by vweevers** [comment]
`rave-level` is shaping up, iterating (as a follower) at twice the speed of `level-party`, bringing it closer to `classic-level`:

<details>
<summary>Click to expand</summary>

![iterate 1647383213299](https://user-images.githubusercontent.com/3055345/158482976-9d1732cd-dcbb-4209-8448-d14bd042bcf3.png)

</details>

**Comment by vweevers** [comment]
Published [`many-level`](https://github.com/Level/many-level).

**Comment by ronag** [comment]
@vweevers any indication on many-level vs local redis perf?

**Comment by vweevers** [comment]
I got side tracked by a Node.js bug on Windows (https://github.com/nodejs/node/issues/42496) but that seems to be an edge case so I went ahead and published [`rave-level`](https://github.com/Level/rave-level).
