### ISSUE TITLE
Handle streams

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-level#2]
Following the [poll result](https://github.com/Level/community/discussions/105):

- [x] Write new [`level-read-stream`](https://github.com/Level/read-stream) module
- [x] ~~Move relevant `levelup` tests there, or _maybe_ add to `abstract-level`~~ Redundant
- [x] Add `level-read-stream` to readme & upgrade guide

**Comment by Raynos** [comment]
Please don't add more dependencies to this package. It already does far too much. The `leveldown` binding does not need streams.
