### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by ronag** [Level/abstract-level#26]
Would be nice if abstract-level could also include benchmarks so we can easily compare our different backend implementations.

**Comment by vweevers** [comment]
See https://github.com/Level/bench - but as I mentioned elsewhere, I need to write some guidelines and/or update docs (because currently level-bench is geared towards the older abstract-leveldown and levelup, and not yet optimized for abstract-level).

**Comment by ronag** [comment]
I assume I need to pass `class` somehow to get it to work with abstract-level

**Comment by ronag** [comment]
Yep. Thanks!
