### ISSUE TITLE
List of available `abstract-level` backends?

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/abstract-level#71]
Is there a list of available `abstract-level` backends anywhere? (similar to the list of [leveldown stores](https://github.com/Level/awesome#stores))

**Comment by vweevers** [comment]
Yeah, didn't get around to updating `awesome` yet. You could check https://www.npmjs.com/package/abstract-level?activeTab=dependents.

**Comment by vweevers** [comment]
I've updated `awesome` (https://github.com/Level/awesome/pull/60) but I didn't add third-party modules. Pull requests are welcome ofc :)
