### ISSUE TITLE
fix levelgraph

### ISSUE THREAD

**Issue by scenaristeur** [Level/abstract-level#73]
i need help to fix levelgraph, see 
 https://github.com/levelgraph/levelgraph/issues/197
according to https://github.com/Level/level/blob/master/UPGRADING.md#streams-have-moved
i've tried to replace leveldb.createValueStream() with leveldb.values() but it does not work 

i've build a test for it https://github.com/scenaristeur/levelgraph/blob/master/test/persist-level/persist_properties_spec%20copy.js

thxs

**Comment by scenaristeur** [comment]
i was using levelgraph that use level for one of my project, but it seems that since level upgrade, levelgraph does not work anymore because it uses the old createValueStream() function, I would like to update the code of levelgrph, but i don't know what/where i have to change
https://github.com/levelgraph/levelgraph/blob/cae97978e4ea2c2db5ab2ef891ce9945325beec5/lib/levelgraph.js#L59 to fix the issue

**Comment by vweevers** [comment]
See https://github.com/Level/read-stream/blob/main/UPGRADING.md
