### ISSUE TITLE
Dependency funding for Abstract-level

### ISSUE THREAD

**Issue by JSeiferth** [Level/abstract-level#74]
First off: Sorry for raising an issue! It's been hard to find a contact method 

**Abstract-Level has received dependency funding from [Optimism](https://github.com/ethereum-optimism), an Ethereum scaling solution**. As part of Optimism's Retroactive Public Goods Funding program, dependencies of the [Optimism Monorepo](https://github.com/ethereum-optimism/optimism) have been awarded OP tokens. 1889.9993 OP have been awarded to you. 

To claim the OP you need to complete a KYC process with the Optimism Foundation. 
Please provide an email address to me, so we can forward you the details. Please reply in this issue or send an email to retropgf@optimism.io 

Thank you ❤️

**Comment by JSeiferth** [comment]
> FYI Optimism has reached out to me too, and after 2 months there is no working KYC yet. I'm in Germany, if we want to claim this it's probably easiest if someone from the US does.

@juliangruber you should def be able to complete the KYC as a German. I sent a follow up e-mail to you. Please let us know if you have any issues (retropgf@optimism.io)

**Comment by vweevers** [comment]
@juliangruber Did you claim it? If not then I'm guessing it expired anyway, so I'll close this.

**Comment by juliangruber** [comment]
I did 👍 and in the end it worked quite smoothly. I don't know if you can still claim it
