### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by ronag** [Level/abstract-level#76]
This doesn't seem to be actively maintained anymore. Any plans to continue development?

**Comment by vweevers** [comment]
I'm on hiatus, just needed a break from open source. I have every intent to return and (among other things) finish `abstract-level` v2. Can't speak for other maintainers.

**Comment by juliangruber** [comment]
I would say we focus on critical bugs and help @vweevers with v2, otherwise this project seems in a good state and doesn't need much maintenance
