### ISSUE TITLE
Wrong Type declarations for .all() and .nextv() methods AbstractKeyIterator and AbstractValueIterator

### ISSUE THREAD

**Issue by bredthau** [Level/abstract-level#86]
According to the typescript declarations the Promise overloads of `.all()` and `.nextv()` of `AbstractKeyIterator` return `Promise<[K]>`. However they should return a promise to an array of type `K` (so `Promise<K[]>` or `Promise<Array<K>>`). Similarly the Callback versions are declared to take `NodeCallback<[K]>` where it should be `NodeCallback<Array<K>>`.
The same situation exists for `AbstractValueIterator`, only with `[V]` where it should be `Array<V>` instead of `[K]`.

**Comment by vweevers** [comment]
PR is welcome. Let's use the `K[]` notation rather than `Array<K>`.
